// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///    options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFCB5js5lKW-5mIkJyyuLZyz2liBxkDo4',
    appId: '1:964738126496:web:58c3b68f087bd2b9de2fc5',
    messagingSenderId: '964738126496',
    projectId: 'study-15534',
    authDomain: 'study-15534.firebaseapp.com',
    storageBucket: 'study-15534.appspot.com',
    measurementId: 'G-5NZRYDVP89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVYa0ANoFPkW6Lm2NRLASgBkVk-sYeGao',
    appId: '1:341188639226:android:624fe06b62fca482994c43',
    messagingSenderId: '341188639226',
    projectId: 'spend-tracker-8a7f1',
    storageBucket: 'spend-tracker-8a7f1.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFCB5js5lKW-5mIkJyyuLZyz2liBxkDo4',
    appId: '1:964738126496:web:35b9dba290841b8bde2fc5',
    messagingSenderId: '964738126496',
    projectId: 'study-15534',
    authDomain: 'study-15534.firebaseapp.com',
    storageBucket: 'study-15534.appspot.com',
    measurementId: 'G-Y1M36V9VSN',
  );
}